name: prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x" # Or stick with "14.x" if required

      - name: Install dependencies
        run: npm ci
        working-directory: ./MtdrSpring/front

      - name: Run Prettier
        run: npm run format
        working-directory: ./MtdrSpring/front

      - name: Commit Prettier changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettier Formatting
          branch: ${{ github.head_ref }}
          file_pattern: ./MtdrSpring/front/**/*.{js,ts,jsx,tsx,json,css,md}
